@host = http://siguna.test/api
# @host = http://194.233.90.213:8124/api	
@host = http://siguna.site/public/api
@token = 07jx2fq7yM0rRcokBhMDGrjzYTNvutoN
# @token = Bwo1NaqaaKTaW7Ip7v83IBFJq82LR3P3
@uname = admin

GET {{host}}/ HTTP/1.1
Accept: application/json

### Login
POST {{host}}/login/ HTTP/1.1
# Accept: application/json
Content-Type: application/x-www-form-urlencoded

username={{uname}}
&password=password

### logout
POST {{host}}/logout HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

### user
GET {{host}}/user HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

### jenis-dokumen
GET {{host}}/md/jenis-dokumen HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

### keluarga
GET {{host}}/md/keluarga HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

### pengajuan dt
GET {{host}}/pengajuan/dt HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

### pengajuan store
POST {{host}}/pengajuan HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json
Content-Type: application/x-www-form-urlencoded

jenis_surat_id=20
&penduduk_id_atas_nama=2
&tujuan_permohonan=testing
&file_bukti=


### pengajuan verif
PUT {{host}}/pengajuan/27/verif HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json
# Content-Type: application/x-www-form-urlencoded

# status=66



### desa cerdas
GET {{host}}/desa-cerdas/dt HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

### layanan kesehatan
GET {{host}}/layanan-kesehatan/dt HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

### layanan kesehatan
GET https://sads.instiki.ac.id/service/tp/sarana-ruangan/get-jadwal-ruang-kelas HTTP/1.1
secret : 2i6eebi78a9e7cfa7dc9deaa795b7d8i958daco8doacio2f9e9oa696edi2fea9eei669e6f8e922b6fifde75d776a276i75b8e9ai67ic8e9827d7ebdo598ibedo
Accept: application/json

